apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authenticator
  template:
    metadata:
      labels:
        app: authenticator
    spec:
      containers:
      - name: authenticator
        image: {{ .Values.authenticator.image }}
        envFrom:
          - secretRef:
              name: {{ .Values.jwt.name }}
        ports:
        - containerPort: 3000