{{- $cert := genSelfSignedCert "" (list) (list) 365  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jwt.name }}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ $cert.Cert | b64enc }}
  tls.key: |
    {{ $cert.Key | b64enc }}